<a href="https://colab.research.google.com/github/samyzistec/Matematicas-para-Ciencia-de-datos/blob/master/Clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([
    [3,2],
    [4,5]])


[[3 2]
 [4 5]]


In [2]:
print(A)

[[3 2]
 [4 5]]


In [3]:
A.shape

(2, 2)

In [7]:
A_listas = [
    [3,2],
    [4,5]]



In [8]:
len(A_listas)

2

In [10]:
B_listas = [
    [4,8],
    [7,9]]

B = np.array([
    [5,7],
    [6,4]])


In [11]:
A + B

array([[ 8,  9],
       [10,  9]])

In [12]:
resultado = 36 * A

In [13]:
resultado

array([[108,  72],
       [144, 180]])

In [14]:
r = 2*A -3*B

In [15]:
r

array([[ -9, -17],
       [-10,  -2]])

In [16]:
r = 0.75 * A

In [17]:
r

array([[2.25, 1.5 ],
       [3.  , 3.75]])

In [19]:
r_redondeado = np.round (r,1)
print(r_redondeado)

[[2.2 1.5]
 [3.  3.8]]


In [20]:
matriz_a = np.array([
    [3,8],
    [6,7]])

matriz_b = np.array([
    [10,23],
    [13,34]])


In [21]:
for i in range(5):
    matriz_b = 0.9 * matriz_b
    matriz_a = matriz_a - matriz_b
    matriz_a = np.round(0.3 * matriz_a, 4)
    print(f"Iteración {i+1}:")
    print("matriz_a =\n", matriz_a)
    print("matriz_b =\n", matriz_b)
    print("------------------------")

Iteración 1:
matriz_a =
 [[-1.8  -3.81]
 [-1.71 -7.08]]
matriz_b =
 [[ 9.  20.7]
 [11.7 30.6]]
------------------------
Iteración 2:
matriz_a =
 [[ -2.97   -6.732]
 [ -3.672 -10.386]]
matriz_b =
 [[ 8.1  18.63]
 [10.53 27.54]]
------------------------
Iteración 3:
matriz_a =
 [[ -3.078   -7.0497]
 [ -3.9447 -10.5516]]
matriz_b =
 [[ 7.29  16.767]
 [ 9.477 24.786]]
------------------------
Iteración 4:
matriz_a =
 [[-2.8917 -6.642 ]
 [-3.7422 -9.8577]]
matriz_b =
 [[ 6.561  15.0903]
 [ 8.5293 22.3074]]
------------------------
Iteración 5:
matriz_a =
 [[-2.639  -6.067 ]
 [-3.4256 -8.9803]]
matriz_b =
 [[ 5.9049  13.58127]
 [ 7.67637 20.07666]]
------------------------
